# Generated by Django 5.1.2 on 2024-11-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitlog",
            name="status",
            field=models.CharField(
                choices=[("C", "Complete"), ("S", "Skipped")], default="C", max_length=1
            ),
        ),
    ]
